# nome da pipeline
name: Execucao de testes

# Momento que será executada
on: 
  pull_request:
    branches: [master]
# O que vai ser feito na Pipeline
# Só tem um job: Rodar os teste
jobs:
  cypress-run:
    # Maquina que será executado
    runs-on: ubuntu-latest

    steps:      
      #clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      #clone do projeto
      - name: Instalar Dependências.
        run: npm install
     
        #execução e config do projeto
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
